name: Build backend and deploy to server

on:
  push:
    branches:
      -  release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 设置 JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 构建 jar 包
        run: mvn clean package -DskipTests -pl spring-ai-demo -am

      - name: 登录 Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login --username=${{ secrets.DOCKER_USERNAME }} --password-stdin ${{ vars.DOCKER_HUB_ADDR }}

      - name: 构建 Docker 镜像
        run: docker build --build-arg PROFILE=${{ env.ENV }} -t ${{ vars.DOCKER_HUB_ADDR }}/${{ vars.DOCKER_NAMESPACE }}/spring-ai-demo:latest .

      - name: 推送 Docker 镜像
        run: docker push ${{ vars.DOCKER_HUB_ADDR }}/${{ vars.DOCKER_NAMESPACE }}/${{ matrix.service }}:${{ env.ENV }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 连接服务器并部署
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /data/spring-ai-demo
            docker compose down
            docker pull ${{ vars.DOCKER_HUB_ADDR }}/${{ vars.DOCKER_NAMESPACE }}/spring-ai-demo:latest
            docker run -d --restart=always --memory=1g --env-file=./.env -e PROJECT_ENV=prod -p 8090:8080 spring-ai-demo:latest
